export const brewMethodPresets = {
  espresso: {
    label: "Espresso",
    description: "Short, concentrated pressure brew with high intensity and body.",
    defaults: {
      dose: 18,
      brewRatio: 2.2,
      grindSize: 18,
      fines: 62,
      roastLevel: 58,
      temperature: 94,
      contactTime: 30,
      pressure: 9,
      pressureAggressiveness: 60,
      preinfusion: 6,
      agitation: 25,
      filterType: "paper",
      bedUniformity: 72,
      channelingRisk: 28,
      extractionEfficiency: 83,
      mineralStrength: 58,
      acidityBuffering: 38,
      bodyEmphasis: 70,
      clarityEmphasis: 45
    },
    coeff: { speed: 1.32, clarity: 0.52, body: 1.22, bitterness: 1.15, aroma: 1.0, immersion: 0.08, windowWidth: 0.32 }
  },
  pourOver: {
    label: "Pour Over",
    description: "Clean, clarity-focused percolation brew with longer contact and controlled flow.",
    defaults: {
      dose: 20,
      brewRatio: 16,
      grindSize: 62,
      fines: 34,
      roastLevel: 42,
      temperature: 93,
      contactTime: 205,
      pressure: 1,
      pressureAggressiveness: 10,
      preinfusion: 35,
      agitation: 48,
      filterType: "paper",
      bedUniformity: 84,
      channelingRisk: 18,
      extractionEfficiency: 75,
      mineralStrength: 60,
      acidityBuffering: 30,
      bodyEmphasis: 42,
      clarityEmphasis: 82
    },
    coeff: { speed: 0.82, clarity: 1.28, body: 0.74, bitterness: 0.92, aroma: 1.06, immersion: 0.22, windowWidth: 0.58 }
  },
  frenchPress: {
    label: "French Press",
    description: "Immersion brew with fuller texture, heavier body, and reduced clarity.",
    defaults: {
      dose: 30,
      brewRatio: 15,
      grindSize: 78,
      fines: 45,
      roastLevel: 50,
      temperature: 94,
      contactTime: 250,
      pressure: 1,
      pressureAggressiveness: 0,
      preinfusion: 0,
      agitation: 58,
      filterType: "metal",
      bedUniformity: 60,
      channelingRisk: 8,
      extractionEfficiency: 72,
      mineralStrength: 56,
      acidityBuffering: 45,
      bodyEmphasis: 82,
      clarityEmphasis: 34
    },
    coeff: { speed: 0.75, clarity: 0.68, body: 1.38, bitterness: 1.03, aroma: 0.96, immersion: 0.95, windowWidth: 0.62 }
  },
  siphon: {
    label: "Siphon",
    description: "Vacuum immersion/percolation hybrid with aromatic emphasis and balanced body.",
    defaults: {
      dose: 22,
      brewRatio: 14,
      grindSize: 56,
      fines: 36,
      roastLevel: 44,
      temperature: 92,
      contactTime: 100,
      pressure: 1.2,
      pressureAggressiveness: 18,
      preinfusion: 12,
      agitation: 36,
      filterType: "cloth",
      bedUniformity: 80,
      channelingRisk: 14,
      extractionEfficiency: 77,
      mineralStrength: 59,
      acidityBuffering: 28,
      bodyEmphasis: 50,
      clarityEmphasis: 69
    },
    coeff: { speed: 0.95, clarity: 1.08, body: 0.92, bitterness: 0.96, aroma: 1.2, immersion: 0.45, windowWidth: 0.48 }
  },
  aeroPress: {
    label: "AeroPress",
    description: "Fast immersion-pressure hybrid with versatile strength and flavor balance.",
    defaults: {
      dose: 17,
      brewRatio: 13,
      grindSize: 48,
      fines: 40,
      roastLevel: 46,
      temperature: 90,
      contactTime: 95,
      pressure: 2,
      pressureAggressiveness: 42,
      preinfusion: 10,
      agitation: 52,
      filterType: "paper",
      bedUniformity: 78,
      channelingRisk: 12,
      extractionEfficiency: 76,
      mineralStrength: 57,
      acidityBuffering: 34,
      bodyEmphasis: 58,
      clarityEmphasis: 62
    },
    coeff: { speed: 1.02, clarity: 0.98, body: 1.0, bitterness: 0.98, aroma: 1.03, immersion: 0.52, windowWidth: 0.44 }
  },
  coldBrew: {
    label: "Cold Brew",
    description: "Low-temperature long extraction emphasizing smoothness and lower perceived acidity.",
    defaults: {
      dose: 80,
      brewRatio: 10,
      grindSize: 82,
      fines: 20,
      roastLevel: 52,
      temperature: 22,
      contactTime: 720,
      pressure: 1,
      pressureAggressiveness: 0,
      preinfusion: 0,
      agitation: 12,
      filterType: "metal",
      bedUniformity: 70,
      channelingRisk: 5,
      extractionEfficiency: 64,
      mineralStrength: 55,
      acidityBuffering: 60,
      bodyEmphasis: 76,
      clarityEmphasis: 40
    },
    coeff: { speed: 0.36, clarity: 0.82, body: 1.12, bitterness: 0.7, aroma: 0.74, immersion: 1.05, windowWidth: 0.74 }
  }
};

export const processPresets = brewMethodPresets;

export const controlConfig = [
  ["dose", "Dose (g)", 8, 90, 1],
  ["brewRatio", "Brew Ratio (water:coffee)", 1.5, 20, 0.1],
  ["grindSize", "Grind Size", 0, 100, 1],
  ["fines", "Fines Amount", 0, 100, 1],
  ["roastLevel", "Roast Level", 0, 100, 1],
  ["temperature", "Water Temperature (°C)", 20, 100, 1],
  ["contactTime", "Contact Time (s)", 20, 1200, 5],
  ["pressure", "Pressure (bar)", 1, 12, 0.1],
  ["pressureAggressiveness", "Pressure Profile Aggressiveness", 0, 100, 1],
  ["preinfusion", "Preinfusion Time (s)", 0, 60, 1],
  ["agitation", "Agitation", 0, 100, 1],
  ["filterType", "Filter Type", ["paper", "cloth", "metal"]],
  ["bedUniformity", "Bed Uniformity", 0, 100, 1],
  ["channelingRisk", "Channeling Risk", 0, 100, 1],
  ["extractionEfficiency", "Extraction Efficiency", 40, 95, 1],
  ["mineralStrength", "Water Mineral Strength", 0, 100, 1],
  ["acidityBuffering", "Acidity Buffering", 0, 100, 1],
  ["bodyEmphasis", "Body Emphasis", 0, 100, 1],
  ["clarityEmphasis", "Clarity Emphasis", 0, 100, 1]
];
